apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest
          image: nest-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nest-backend-service
spec:
  selector:
    app: nest-backend
  ports:
    - port: 3000
      targetPort: 3000
